#!/usr/bin/python3
from tkinter import *
from tkinter import filedialog
from tkinter import messagebox

def new():
    text_box.delete(1.0, END)

def savefile():
    name = filedialog.asksaveasfilename()
    try:
        file = open(name, 'w')
        file.write(text_box.get("1.0", END))
        file.close()
    except:
        print("Все плохо, Вы не сохранили файл")

def openfile():
    name = filedialog.askopenfilename()
    try:
        file = open(name, 'r')
        text_box.delete(1.0, END)
        text_box.insert('1.0', file.read())
    except:
        print('test_text2.txt')

def adout():
    messagebox.showinfo("О программе", "Текстовый редактор. My first time try")

def helpwin():
    helper = Toplevel(ws)
    helper.title('Файл помощи')
    text_help = Text(helper)
    text_help.pack(fill='both', expand=True)
    file = open('help.txt', 'r')
    text_help.delete(1.0, END)
    text_help.insert('1.0', file.read())
    text_help.configure(state='disable')


ws = Tk()
ws.title("Text editor")
ws.geometry('640x480')

mainmenu = Menu()
filemenu = Menu(mainmenu, tearoff=0)
filemenu.add_command(label="Открыть", command=openfile)
filemenu.add_command(label="Новый", command=new)
filemenu.add_command(label="Сохранить", command=savefile)
filemenu.add_command(label="Выход", command=ws.destroy)

helpmenu = Menu(mainmenu, tearoff=0)
helpmenu.add_command(label="Помощь", command=helpwin)
helpmenu.add_command(label="О программе", command=adout)

mainmenu.add_cascade(label="Файл", menu=filemenu)
mainmenu.add_cascade(label="Справка", menu=helpmenu)

ws.config(menu=mainmenu)

text_box = Text(ws)
scrollbar = Scrollbar(text_box)
scrollbar['command'] = text_box.yview
text_box['yscrollcommand'] = scrollbar.set
text_box.pack(fill='both', expand=True)
scrollbar.pack(side='right', fill='y')

Button(text='Закрыть', command=ws.destroy).pack(side='left')

ws.mainloop()
